"""empty message

Revision ID: 2376fd05260c
Revises: 29b0ca97bcb3
Create Date: 2023-01-27 21:55:21.728061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2376fd05260c'
down_revision = '29b0ca97bcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=700), nullable=True))
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
